import * as T from 'three';
import { prep, merge, ID, M } from './geo';
import { uber } from '../render/materials';
import { clone } from 'three/examples/jsm/utils/SkeletonUtils.js';
import { DeerGait } from './deer-gait';
import { HABITATS, type HabitatDefinition, type HabitatSpecies } from '../data/habitats';
import {
  validateHabitatSave,
  type HabitatState,
  type HabitatSave,
  type HabitatRecord,
} from '../data/habitat-save';
export type { HabitatState, HabitatSave, HabitatRecord } from '../data/habitat-save';
interface Position {
  x: number;
  y: number;
  z: number;
}
export interface HabitatAsset {
  scene: T.Object3D;
  animations?: T.AnimationClip[];
  contactY?: number;
}
export interface HabitatOptions {
  terrainHeight: (x: number, z: number) => number;
  waterHeight: (x: number, z: number) => number | null;
  /** Solid geometry only: do not treat the water surface as an obstacle. */
  blocked: (x: number, y: number, z: number, radius: number) => boolean;
  assets?: Partial<Record<HabitatSpecies, HabitatAsset>>;
  saved?: unknown;
  drawDistance?: number;
  habitats?: readonly HabitatDefinition[];
}
export interface HabitatSupportObstacle {
  readonly x: number;
  readonly z: number;
  readonly r: number;
  readonly bottom: number;
  readonly height: number;
  readonly tag: string;
}
interface Animal {
  definition: HabitatDefinition;
  record: HabitatRecord;
  root: T.Group;
  model?: T.Object3D;
  mixer?: T.AnimationMixer;
  action?: T.AnimationAction;
  clipState?: string;
  deerGait?: DeerGait;
  previous: Position;
  joints: Map<string, { object: T.Object3D; rotation: T.Euler }>;
}
const copy = (p: Position): Position => ({ ...p });
const distance = (a: Position, b: Position) => Math.hypot(a.x - b.x, a.y - b.y, a.z - b.z);
const smooth = (v: number) => v * v * (3 - 2 * v);
// Metres from the measured soles to the surface; head and upper shell stay above water.
const TERRAPIN_DRAFT = 0.1;
const groundRadius = (a: Animal) => (a.definition.species === 'deer' ? 1.6 : 0.5);
const distanceToSegment = (p: Position, a: Position, b: Position) => {
  const dx = b.x - a.x,
    dz = b.z - a.z;
  const t = Math.max(
    0,
    Math.min(1, ((p.x - a.x) * dx + (p.z - a.z) * dz) / Math.max(1e-9, dx * dx + dz * dz)),
  );
  return Math.hypot(p.x - a.x - dx * t, p.z - a.z - dz * t);
};
/** Resident simulation is independent of render visibility. No world obstacle is mutated. */
export class HabitatLife {
  readonly group = new T.Group();
  /** Add once to the shared world collision after construction; never regenerated by reset. */
  readonly supportObstacles: readonly HabitatSupportObstacle[];
  drawDistance: number;
  private animals: Animal[] = [];
  private initialRecords: HabitatRecord[] = [];
  private elapsed = 0;
  private remainder = 0;
  private supports: T.Mesh[] = [];
  private supportSolids: {
    x: number;
    z: number;
    bottom: number;
    top: number;
    radius: number;
    tag: string;
  }[] = [];
  constructor(private options: HabitatOptions) {
    this.group.name = 'Regional habitat life';
    this.drawDistance = options.drawDistance ?? 150;
    for (const source of options.habitats ?? HABITATS)
      for (let i = 0; i < source.count; i++) {
        const definition =
          source.species === 'songbird'
            ? {
                ...source,
                points: source.points.map((p) => ({
                  ...p,
                  x: p.x + (i % 2) * 0.7,
                  z: p.z + Math.floor(i / 2) * 0.7,
                  previousPosition: p.previousPosition
                    ? {
                        x: p.previousPosition.x + (i % 2) * 0.7,
                        z: p.previousPosition.z + Math.floor(i / 2) * 0.7,
                      }
                    : undefined,
                })),
              }
            : source;
        const node = definition.species === 'songbird' ? 0 : i % definition.points.length,
          position = this.point(definition, node);
        const root = new T.Group();
        this.group.add(root);
        const record: HabitatRecord = {
          id: `${definition.id}-${i}`,
          state: definition.species === 'songbird' ? 'perch' : 'rest',
          age: 0,
          node,
          target: node,
          position,
          origin: copy(position),
          duration: 10 + i * 0.35,
          cycle: 0,
          cooldown: 0,
        };
        const animal: Animal = { definition, record, root, previous: copy(position), joints: new Map() };
        const asset = options.assets?.[definition.species];
        if (asset) {
          animal.model = clone(asset.scene);
          animal.model.position.y -= asset.contactY ?? 0;
          root.add(animal.model);
          animal.model.traverse((o) => {
            if (/Pivot|Leg_|Knee_|Hoof_|Wing_|WingTip_/.test(o.name))
              animal.joints.set(o.name.replace(/^(deer|terrapin|songbird)_/, ''), {
                object: o,
                rotation: o.rotation.clone(),
              });
          });
          if (asset.animations?.length) animal.mixer = new T.AnimationMixer(animal.model);
          if (definition.species === 'deer')
            animal.deerGait = DeerGait.create(root, animal.model, options.terrainHeight);
        }
        root.position.copy(position);
        this.animals.push(animal);
      }
    for (const source of options.habitats ?? HABITATS) {
      const rocks: T.BufferGeometry[] = [];
      for (const a of this.animals.filter((a) => a.definition.id === source.id))
        for (const p of a.definition.points) {
          if (!p.perchHeight) continue;
          const ground = options.terrainHeight(p.x, p.z);
          this.supportSolids.push({
            x: p.x,
            z: p.z,
            bottom: ground - 0.15,
            top: ground + p.perchHeight,
            radius: 0.39,
            tag: `${source.id}:perch:${p.x}:${p.z}`,
          });
          const g = prep(
            new T.CylinderGeometry(0.24, 0.39, p.perchHeight + 0.15, 7),
            source.id.startsWith('crown') ? '#858a82' : '#738371',
            M.plain,
          );
          g.translate(p.x, options.terrainHeight(p.x, p.z) + (p.perchHeight - 0.15) / 2, p.z);
          rocks.push(g);
        }
      if (rocks.length) {
        const mesh = new T.Mesh(merge(rocks), uber(ID.house, 0));
        mesh.name = source.id + ' perch stones';
        mesh.geometry.computeBoundingSphere();
        this.supports.push(mesh);
        this.group.add(mesh);
      }
    }
    this.supportObstacles = Object.freeze(
      this.supportSolids.map((s) =>
        Object.freeze({
          x: s.x,
          z: s.z,
          r: s.radius,
          bottom: s.bottom,
          height: s.top - s.bottom,
          tag: s.tag,
        }),
      ),
    );
    for (const a of this.animals) this.repairGroundContact(a);
    this.initialRecords = this.snapshot().animals;
    if (options.saved) this.restore(options.saved);
    for (const a of this.animals) this.poseNow(a);
  }
  private point(d: HabitatDefinition, node: number): Position {
    const p = d.points[node],
      ground = this.options.terrainHeight(p.x, p.z),
      water = this.options.waterHeight(p.x, p.z);
    return {
      x: p.x,
      y: p.water && water !== null ? Math.max(ground, water - TERRAPIN_DRAFT) : ground + (p.perchHeight ?? 0),
      z: p.z,
    };
  }
  private safe(d: HabitatDefinition, p: Position, air = false) {
    // The deer head/hooves extend well beyond its old .38m root cylinder.
    // Perch stones are owned geometry, absent from the external scenery query.
    const radius = d.species === 'deer' ? 1.6 : d.radius;
    if (
      !Number.isFinite(p.y) ||
      (air && p.y < this.options.terrainHeight(p.x, p.z) - 0.02) ||
      this.options.blocked(p.x, p.y + 0.12, p.z, radius) ||
      (d.species !== 'songbird' &&
        this.supportSolids.some(
          (s) => p.y < s.top && p.y + 1.5 > s.bottom && Math.hypot(p.x - s.x, p.z - s.z) < radius + s.radius,
        ))
    )
      return false;
    const water = this.options.waterHeight(p.x, p.z);
    if (air) return true;
    return d.species === 'terrapin' ? true : water === null || water <= p.y + 0.03;
  }
  private repairGroundContact(a: Animal) {
    if (a.definition.species === 'songbird' || this.safe(a.definition, a.record.position)) return;
    const node = a.definition.points.findIndex((_, i) => {
      const p = this.point(a.definition, i);
      return this.safe(a.definition, p) && !this.occupied(a, p, true);
    });
    if (node < 0) return;
    const p = this.point(a.definition, node);
    a.record.node = a.record.target = node;
    a.record.position = copy(p);
    a.record.origin = copy(p);
    a.previous = copy(p);
    this.enter(a, 'rest', 5);
  }
  /** Ground animals reserve their remaining corridor as well as their destination.
   * This prevents a feeding animal or an approaching neighbour occupying the same
   * contact. Reservations derive entirely from saved state, including offscreen. */
  private occupied(a: Animal, p: Position, corridors = false) {
    if (a.definition.species === 'songbird') return false;
    return this.animals.some((other) => {
      if (other === a || other.record.id === a.record.id || other.definition.species === 'songbird')
        return false;
      const end =
        corridors && other.record.state === 'wander'
          ? this.point(other.definition, other.record.target)
          : other.record.position;
      return distanceToSegment(p, other.record.position, end) < groundRadius(a) + groundRadius(other) + 0.08;
    });
  }
  private route(a: Animal, target: number, air = false, avoidResidents = false) {
    const start = a.record.position,
      end = this.point(a.definition, target),
      length = distance(start, end);
    let previousY = start.y;
    for (let i = 1; i <= Math.max(1, Math.ceil(length / (air ? 0.15 : 0.3))); i++) {
      const t = i / Math.max(1, Math.ceil(length / (air ? 0.15 : 0.3))),
        x = start.x + (end.x - start.x) * (air ? smooth(t) : t),
        z = start.z + (end.z - start.z) * (air ? smooth(t) : t);
      const ground = this.options.terrainHeight(x, z),
        water = this.options.waterHeight(x, z);
      const y = air
        ? start.y + (end.y - start.y) * smooth(t) + Math.sin(Math.PI * t) * 5
        : a.definition.species === 'terrapin' && water !== null
          ? Math.max(ground, water - TERRAPIN_DRAFT)
          : ground;
      if (!this.safe(a.definition, { x, y, z }, air)) return false;
      if (avoidResidents && this.occupied(a, { x, y, z }, true)) return false;
      if (!air && Math.abs(y - previousY) > 0.45) return false;
      previousY = y;
    }
    return true;
  }
  private enter(a: Animal, state: HabitatState, duration: number) {
    a.record.state = state;
    a.record.age = 0;
    a.record.duration = duration;
  }
  private depart(a: Animal, player?: Position) {
    const r = a.record,
      d = a.definition,
      air = d.species === 'songbird';
    let choices = d.points.map((_, i) => i).filter((i) => i !== r.node);
    if (player)
      choices.sort((i, j) => distance(this.point(d, j), player) - distance(this.point(d, i), player));
    else choices = choices.slice(r.cycle % choices.length).concat(choices.slice(0, r.cycle % choices.length));
    const target = choices.find((i) => this.route(a, i, air, !air));
    if (target === undefined) {
      this.enter(a, air ? 'perch' : 'rest', 5);
      return;
    }
    r.target = target;
    r.origin = copy(r.position);
    r.cycle++;
    this.enter(
      a,
      air ? 'takeoff' : 'wander',
      Math.max(air ? 4 : 1, distance(r.position, this.point(d, target)) / d.speed),
    );
  }
  /** day is normalized solar time: 0 midnight, .5 noon. dt is unscaled game seconds. */
  update(dt: number, day: number, player: Position) {
    if (!Number.isFinite(dt) || dt < 0) return;
    this.remainder += Math.min(dt, 3600);
    while (this.remainder >= 0.1) {
      this.remainder -= 0.1;
      this.elapsed += 0.1;
      for (const a of this.animals) {
        a.previous = copy(a.record.position);
        this.step(a, 0.1, day, player);
      }
    }
    for (const mesh of this.supports)
      mesh.visible = distance(mesh.geometry.boundingSphere!.center, player) < this.drawDistance + 25;
    for (const a of this.animals) {
      a.root.position.set(
        T.MathUtils.lerp(a.previous.x, a.record.position.x, this.remainder / 0.1),
        T.MathUtils.lerp(a.previous.y, a.record.position.y, this.remainder / 0.1),
        T.MathUtils.lerp(a.previous.z, a.record.position.z, this.remainder / 0.1),
      );
      a.root.visible = distance(a.record.position, player) < this.drawDistance;
      if (a.root.visible || a.deerGait) this.animate(a, Math.min(dt, 0.2));
    }
  }
  private step(a: Animal, dt: number, day: number, player: Position) {
    const r = a.record,
      d = a.definition,
      bird = d.species === 'songbird';
    r.age += dt;
    r.cooldown = Math.max(0, r.cooldown - dt);
    const flying = ['takeoff', 'flock', 'land'].includes(r.state);
    if (
      !flying &&
      r.state !== 'react' &&
      r.cooldown === 0 &&
      distance(r.position, player) < (bird ? 3.5 : d.species === 'deer' ? 4 : 1.8)
    ) {
      r.cooldown = 18;
      this.enter(a, 'react', bird ? 0.5 : d.species === 'deer' ? 1.6 : 2);
      return;
    }
    if (r.state === 'react') {
      if (r.age >= r.duration) this.depart(a, player);
      return;
    }
    if (flying) {
      const t = Math.min(1, r.age / r.duration),
        end = this.point(d, r.target);
      const p = {
        x: r.origin.x + (end.x - r.origin.x) * smooth(t),
        z: r.origin.z + (end.z - r.origin.z) * smooth(t),
        y: r.origin.y + (end.y - r.origin.y) * smooth(t) + Math.sin(Math.PI * t) * 5,
      };
      if (!this.safe(d, p, true)) {
        r.age -= dt;
        return;
      }
      r.position = p;
      r.state = t < 0.18 ? 'takeoff' : t > 0.8 ? 'land' : 'flock';
      a.root.rotation.y = Math.atan2(end.x - r.origin.x, end.z - r.origin.z);
      if (t === 1) {
        r.node = r.target;
        r.position = end;
        this.enter(a, 'perch', 14 + (r.cycle % 4) * 3);
      }
      return;
    }
    if (r.state === 'wander') {
      const end = this.point(d, r.target),
        dx = end.x - r.position.x,
        dz = end.z - r.position.z,
        len = Math.hypot(dx, dz),
        step = Math.min(len, d.speed * dt);
      const x = r.position.x + (dx / Math.max(0.0001, len)) * step,
        z = r.position.z + (dz / Math.max(0.0001, len)) * step;
      const ground = this.options.terrainHeight(x, z),
        water = this.options.waterHeight(x, z),
        y = d.species === 'terrapin' && water !== null ? Math.max(ground, water - TERRAPIN_DRAFT) : ground;
      if (!this.safe(d, { x, y, z }) || Math.abs(y - r.position.y) > 0.3 || this.occupied(a, { x, y, z })) {
        this.enter(a, 'rest', 4);
        return;
      }
      r.position = { x, y, z };
      a.root.rotation.y = Math.atan2(dx, dz);
      if (len < 0.03) {
        r.node = r.target;
        this.enter(a, 'feed', 8 + (r.cycle % 5));
      }
      return;
    }
    if (r.age < r.duration) return;
    const night = day < 0.2 || day > 0.82;
    if (night) {
      this.enter(a, bird ? 'perch' : 'rest', 12);
      return;
    }
    if (r.state === 'feed') this.enter(a, 'rest', 6 + (r.cycle % 7));
    else this.depart(a);
  }
  private animate(a: Animal, dt: number, immediate = false) {
    const r = a.record,
      asset = this.options.assets?.[a.definition.species];
    const clipName =
      r.state === 'wander' ? 'walk' : r.state === 'flock' ? 'fly' : r.state === 'perch' ? 'perched' : r.state;
    const clip = asset?.animations?.find((c) => c.name.toLowerCase() === clipName);
    if (clip && a.mixer) {
      if (a.clipState !== clipName) {
        const action = a.mixer.clipAction(clip);
        action.reset().fadeIn(0.25).play();
        a.action?.fadeOut(0.25);
        a.action = action;
        a.clipState = clipName;
      }
      a.mixer.update(dt);
      a.deerGait?.update(dt, r.state === 'wander', immediate);
      return;
    }
    const gait = Math.sin(this.elapsed * (a.definition.species === 'terrapin' ? 3 : 6)),
      moving = r.state === 'wander',
      flight = ['takeoff', 'flock', 'land'].includes(r.state);
    const weight = Math.min(1, r.age * 3);
    for (const [name, j] of a.joints) {
      if (a.deerGait && /^(Leg_|Knee_|Hoof_)/.test(name)) continue;
      let x = 0,
        y = 0,
        z = 0;
      if (name.startsWith('Leg_') && moving)
        x = gait * (name.endsWith('FL') || name.endsWith('BR') ? 1 : -1) * 0.35 * weight;
      if (name === 'NeckPivot' && r.state === 'feed')
        x = (a.definition.species === 'deer' ? 1.35 : 0.65) * weight;
      if (name === 'HeadPivot')
        x =
          r.state === 'feed'
            ? ((a.definition.species === 'deer' ? 0.15 : 0) + 0.04 * Math.sin(this.elapsed * 2)) * weight
            : r.state === 'react'
              ? -0.18 * weight
              : 0.03 * Math.sin(this.elapsed);
      if (/^Wing_[LR]$/.test(name)) {
        const side = name.endsWith('L') ? 1 : -1;
        y = flight ? 0 : -side * 1.2;
        z = flight
          ? side * (0.25 + Math.sin(this.elapsed * 22) * 0.65) * Math.min(1, r.age * 5)
          : side * 0.25;
      }
      if (/^WingTip_[LR]$/.test(name) && flight)
        z = (name.endsWith('L') ? 1 : -1) * Math.sin(this.elapsed * 22 - 0.6) * 0.2;
      const blend = immediate ? 1 : 1 - Math.exp(-dt * 10);
      j.object.rotation.x = T.MathUtils.lerp(j.object.rotation.x, j.rotation.x + x, blend);
      j.object.rotation.y = T.MathUtils.lerp(j.object.rotation.y, j.rotation.y + y, blend);
      j.object.rotation.z = T.MathUtils.lerp(j.object.rotation.z, j.rotation.z + z, blend);
    }
    a.deerGait?.update(dt, moving, immediate);
  }
  private poseNow(a: Animal) {
    a.root.position.copy(a.record.position);
    if (['wander', 'takeoff', 'flock', 'land'].includes(a.record.state)) {
      const end = this.point(a.definition, a.record.target);
      a.root.rotation.y = Math.atan2(end.x - a.record.position.x, end.z - a.record.position.z);
    }
    this.animate(a, 0, true);
  }
  snapshot(): HabitatSave {
    return {
      version: 1,
      elapsed: this.elapsed,
      animals: this.animals.map((a) => ({
        ...a.record,
        position: copy(a.record.position),
        origin: copy(a.record.origin),
      })),
    };
  }
  inspect() {
    return this.snapshot();
  }
  /** Only migrate records that exactly match a known previous authored contact
   * or flight. Unchanged flights keep their phase; affected flights rest on a
   * real support before departing again, retaining their cycle and cooldown. */
  private migrateBirdContact(d: HabitatDefinition, r: HabitatRecord) {
    if (d.species !== 'songbird' || !d.points.some((p) => p.previousPosition)) return;
    const old = {
      ...d,
      points: d.points.map((p) => ({ ...p, ...p.previousPosition })),
    };
    const flying = ['takeoff', 'flock', 'land'].includes(r.state);
    const start = this.point(d, r.node),
      oldStart = this.point(old, r.node);
    if (!flying) {
      if (distance(start, oldStart) < 0.03 || distance(r.position, oldStart) > 0.03) return;
      r.position = copy(start);
      r.origin = copy(start);
      r.target = r.node;
      return;
    }
    const end = this.point(d, r.target),
      oldEnd = this.point(old, r.target);
    if (distance(start, oldStart) < 0.03 && distance(end, oldEnd) < 0.03) return;
    const t = Math.min(1, r.age / r.duration),
      current = {
        x: start.x + (end.x - start.x) * smooth(t),
        y: start.y + (end.y - start.y) * smooth(t) + Math.sin(Math.PI * t) * 5,
        z: start.z + (end.z - start.z) * smooth(t),
      },
      expected = {
        x: oldStart.x + (oldEnd.x - oldStart.x) * smooth(t),
        y: oldStart.y + (oldEnd.y - oldStart.y) * smooth(t) + Math.sin(Math.PI * t) * 5,
        z: oldStart.z + (oldEnd.z - oldStart.z) * smooth(t),
      };
    if (distance(r.origin, start) <= 0.03 && distance(r.position, current) <= 0.03) return;
    if (distance(r.origin, oldStart) > 0.03 || distance(r.position, expected) > 0.03) return;
    r.position = copy(start);
    r.origin = copy(start);
    r.target = r.node;
    r.state = 'perch';
    r.age = 0;
    r.duration = 5;
  }
  private restore(value: unknown) {
    const save = validateHabitatSave(value, this.options.habitats ?? HABITATS);
    this.elapsed = save.elapsed;
    for (const a of this.animals) {
      const r = save.animals.find((r) => r.id === a.record.id),
        d = a.definition;
      if (!r) continue;
      this.migrateBirdContact(d, r);
      const air = ['takeoff', 'flock', 'land'].includes(r.state);
      if (d.species === 'songbird' && !air && distance(r.position, this.point(d, r.node)) > 0.03)
        continue;
      const ground = this.options.terrainHeight(r.position.x, r.position.z),
        water = this.options.waterHeight(r.position.x, r.position.z);
      const contact =
        d.species === 'terrapin' && water !== null
          ? Math.max(ground, water - TERRAPIN_DRAFT)
          : ground + (d.species === 'songbird' ? (d.points[r.node].perchHeight ?? 0) : 0);
      // Migrate the earlier candidate's submerged waterline without losing its route/history.
      if (d.species === 'terrapin' && water !== null && Math.abs(r.position.y - contact) <= 0.15)
        r.position.y = contact;
      if (!air && Math.abs(r.position.y - contact) > 0.05) continue;
      if (
        air &&
        (r.position.y < ground - 0.02 ||
          r.position.y > Math.max(this.point(d, r.node).y, this.point(d, r.target).y) + 5.1)
      )
        continue;
      if (!this.safe(d, r.position, air)) continue;
      if (air) {
        const t = Math.min(1, r.age / r.duration),
          end = this.point(d, r.target);
        const expected = {
          x: r.origin.x + (end.x - r.origin.x) * smooth(t),
          z: r.origin.z + (end.z - r.origin.z) * smooth(t),
          y: r.origin.y + (end.y - r.origin.y) * smooth(t) + Math.sin(Math.PI * t) * 5,
        };
        if (distance(expected, r.position) > 0.03 || distance(r.origin, this.point(d, r.node)) > 0.03)
          continue;
        if (!this.route({ ...a, record: { ...r, position: r.origin } }, r.target, true)) continue;
      } else if (r.state === 'wander' && !this.route({ ...a, record: r }, r.target)) continue;
      a.record = { ...r, position: copy(r.position), origin: copy(r.origin) };
      a.previous = copy(r.position);
      a.root.position.copy(r.position);
    }
    // Old candidates could save two residents on the same feeding node. Repair
    // only those contacts at load, keeping all valid histories and flight phases.
    for (const a of this.animals) {
      if (!this.occupied(a, a.record.position)) continue;
      const node = a.definition.points.findIndex((_, i) => {
        const p = this.point(a.definition, i);
        return this.safe(a.definition, p) && !this.occupied(a, p, true);
      });
      if (node < 0) continue;
      const p = this.point(a.definition, node);
      a.record.node = a.record.target = node;
      a.record.position = copy(p);
      a.record.origin = copy(p);
      a.previous = copy(p);
      this.enter(a, 'rest', 5);
    }
  }
  reset() {
    this.elapsed = 0;
    this.remainder = 0;
    for (let i = 0; i < this.animals.length; i++) {
      const a = this.animals[i],
        r = this.initialRecords[i];
      a.record = { ...r, position: copy(r.position), origin: copy(r.origin) };
      a.previous = copy(r.position);
      a.root.position.copy(r.position);
      a.root.rotation.set(0, 0, 0);
      a.mixer?.stopAllAction();
      a.action = undefined;
      a.clipState = undefined;
      for (const joint of a.joints.values()) joint.object.rotation.copy(joint.rotation);
      a.deerGait?.reset();
      this.poseNow(a);
    }
  }
  dispose() {
    for (const a of this.animals) a.mixer?.stopAllAction();
    for (const mesh of this.supports) mesh.geometry.dispose();
    this.group.removeFromParent();
    this.group.clear();
  }
}
